# Generated by Django 3.0.2 on 2020-01-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='E-mail')),
                ('password', models.CharField(max_length=100, verbose_name='Password Hash')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Not Declared')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('random', models.BooleanField(default=False, verbose_name='Random Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranrem.User')),
            ],
        ),
    ]
