# Generated by Django 3.1.5 on 2021-01-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='BasicNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.account')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('basicnote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.basicnote')),
                ('text', models.TextField(verbose_name='Text')),
            ],
            bases=('notes.basicnote',),
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('basicnote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.basicnote')),
                ('count', models.IntegerField(default=0, verbose_name='Total items')),
            ],
            bases=('notes.basicnote',),
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Item')),
                ('checked', models.BooleanField(default=False, verbose_name='Checked')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.todolist')),
            ],
        ),
    ]
