BEGIN;

DROP TABLE IF EXISTS "Edge";
DROP TABLE IF EXISTS "Lesson_Tasks";
DROP TABLE IF EXISTS "CompletedLessons";
DROP TABLE IF EXISTS "DoneTasks";
DROP TABLE IF EXISTS "Task";
DROP TABLE IF EXISTS "UserExt";
DROP TABLE IF EXISTS "Lesson";
DROP TABLE IF EXISTS "Author";
DROP TABLE IF EXISTS "Stage";
DROP TABLE IF EXISTS "Topic";
DROP TABLE IF EXISTS "User";

COMMIT;