BEGIN;

--
-- Clear database
--
DROP TABLE IF EXISTS "Edge";
DROP TABLE IF EXISTS "Lesson_Tasks";
DROP TABLE IF EXISTS "CompletedLessons";
DROP TABLE IF EXISTS "DoneTasks";
DROP TABLE IF EXISTS "Task";
DROP TABLE IF EXISTS "UserExt";
DROP TABLE IF EXISTS "Lesson";
DROP TABLE IF EXISTS "Author";
DROP TABLE IF EXISTS "Stage";
DROP TABLE IF EXISTS "Topic";
DROP TABLE IF EXISTS "User";

--
-- Create model user
--
CREATE TABLE "User" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "username" varchar(50) NOT NULL UNIQUE,
    "email" varchar(50) NOT NULL UNIQUE,
    "password_hash" varchar(100) NOT NULL,
    "first_name" varchar(50), "last_name" varchar(50));

--
-- Create model UserExt
--
CREATE TABLE "UserExt" (
    "user_id" integer NOT NULL PRIMARY KEY,
    "codeforces" varchar(50) NULL,
    "infoarena" varchar(50) NULL,
    "varena" varchar(50) NULL);

ALTER TABLE "UserExt" ADD CONSTRAINT "UserExt_User_id_fk_User_id"
    FOREIGN KEY ("user_id") REFERENCES "User" ("id") DEFERRABLE INITIALLY DEFERRED;

--
-- Create model Author
--
CREATE TABLE "Author" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(50) NOT NULL,
    "user_id" integer NULL UNIQUE);

ALTER TABLE "Author" ADD CONSTRAINT "Author_user_id_fk_User_id"
    FOREIGN KEY ("user_id") REFERENCES "User" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Author_user_id" ON "Author" ("user_id");

--
-- Create model Stage
--
CREATE TABLE "Stage" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(50) NOT NULL,
    "index" integer NOT NULL UNIQUE);

--
-- Create model Topic
--
CREATE TABLE "Topic" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "topo_order" varchar(200) NOT NULL,
    "supertopic_id" integer NULL);

ALTER TABLE "Topic" ADD CONSTRAINT "Topic_supertopic_id_fk_Topic_id"
    FOREIGN KEY ("supertopic_id") REFERENCES "Topic" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Topic_supertopic_id" ON "Topic" ("supertopic_id");

--
-- Create model Task
--
CREATE TABLE "Task" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(50) NOT NULL,
    "source" varchar(50) NOT NULL,
    "description" text NULL,
    "link" varchar(200) NOT NULL UNIQUE,
    "solution" varchar(200) NULL,
    "tags" text NULL,
    "hints" boolean NOT NULL DEFAULT false,
    "hint1" text NULL, "hint2" text NULL, "hint3" text NULL);

CREATE INDEX "Task_link_like" ON "Task" ("link" varchar_pattern_ops);

--
-- Create model Lesson
--
CREATE TABLE "Lesson" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(100) NOT NULL,
    "duration" interval NULL,
    "content" text NULL,
    "link_to_code" varchar(200) NULL,
    "author_id" integer NULL,
    "stage_id" integer NOT NULL,
    "topic_id" integer NOT NULL);

ALTER TABLE "Lesson" ADD CONSTRAINT "Lesson_author_id_fk_Author_id"
    FOREIGN KEY ("author_id") REFERENCES "Author" ("id")
        ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Lesson_author_id" ON "Lesson" ("author_id");

ALTER TABLE "Lesson" ADD CONSTRAINT "Lesson_stage_fk_Stage_id"
    FOREIGN KEY ("stage_id") REFERENCES "Stage" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Lesson_stage_id" ON "Lesson" ("stage_id");

ALTER TABLE "Lesson" ADD CONSTRAINT "Lesson_topic_id_fk_Topic_id"
    FOREIGN KEY ("topic_id") REFERENCES "Topic" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Lesson_topic_id" ON "Lesson" ("topic_id");

CREATE INDEX "Lesson_link_like" ON "Lesson" ("link_to_code" varchar_pattern_ops);

--
-- Create model Lesson_Tasks
--
CREATE TABLE "Lesson_Tasks" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "lesson_id" integer NOT NULL,
    "task_id" integer NOT NULL);

ALTER TABLE "Lesson_Tasks" ADD CONSTRAINT "Lesson_Tasks_lesson_id_task_id_uniq"
    UNIQUE ("lesson_id", "task_id");

ALTER TABLE "Lesson_Tasks" ADD CONSTRAINT "Lesson_Tasks_lesson_id_fk_Lesson_id"
    FOREIGN KEY ("lesson_id") REFERENCES "Lesson" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Lesson_Tasks_lesson_id" ON "Lesson_Tasks" ("lesson_id");

ALTER TABLE "Lesson_Tasks" ADD CONSTRAINT "Lesson_Tasks_task_id_fk_Task_id"
    FOREIGN KEY ("task_id") REFERENCES "Task" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Lesson_Tasks_task_id" ON "Lesson_Tasks" ("task_id");

--
-- Create model Edge
--
CREATE TABLE "Edge" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "hidden" boolean NOT NULL DEFAULT false,
    "src_id" integer NOT NULL,
    "dest_id" integer NOT NULL);

ALTER TABLE "Edge" ADD CONSTRAINT "Edge_src_id_dest_id_uniq"
    UNIQUE ("src_id", "dest_id");

ALTER TABLE "Edge" ADD CONSTRAINT "Edge_dest_id_fk_Lesson_id"
    FOREIGN KEY ("dest_id") REFERENCES "Lesson" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Edge_dest_id" ON "Edge" ("dest_id");

ALTER TABLE "Edge" ADD CONSTRAINT "Edge_src_id_fk_Lesson_id"
    FOREIGN KEY ("src_id") REFERENCES "Lesson" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Edge_src_id" ON "Edge" ("src_id");

--
-- Create model DoneTasks
--
CREATE TABLE "DoneTasks" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "task_id" integer NOT NULL,
    "user_id" integer NOT NULL);

ALTER TABLE "DoneTasks" ADD CONSTRAINT "DoneTasks_task_id_user_id_uniq"
    UNIQUE ("task_id", "user_id");

ALTER TABLE "DoneTasks" ADD CONSTRAINT "DoneTasks_task_id_fk_Task_id"
    FOREIGN KEY ("task_id") REFERENCES "Task" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "DoneTasks_task_id" ON "DoneTasks" ("task_id");

ALTER TABLE "DoneTasks" ADD CONSTRAINT "DoneTasks_user_id_fk_User_id"
    FOREIGN KEY ("user_id") REFERENCES "User" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "DoneTasks_user_id" ON "DoneTasks" ("user_id");

--
-- Create model CompletedLessons
--
CREATE TABLE "CompletedLessons" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "in_progress" boolean NOT NULL,
    "lesson_id" integer NOT NULL,
    "user_id" integer NOT NULL);

ALTER TABLE "CompletedLessons" ADD CONSTRAINT "CompletedLessons_lesson_id_user_id_uniq"
    UNIQUE ("lesson_id", "user_id");

ALTER TABLE "CompletedLessons" ADD CONSTRAINT "CompletedLessons_lesson_id_fk_Lesson_id"
    FOREIGN KEY ("lesson_id") REFERENCES "Lesson" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "CompletedLessons_lesson_id" ON "CompletedLessons" ("lesson_id");

ALTER TABLE "CompletedLessons" ADD CONSTRAINT "CompletedLessons_user_id_fk_User_id"
    FOREIGN KEY ("user_id") REFERENCES "User" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "CompletedLessons_user_id" ON "CompletedLessons" ("user_id");

COMMIT;